### ISSUE TITLE
 Error when running on Windows 10

### ISSUE THREAD

**Issue by leeisack** [RameenAbdal/StyleFlow#118]
If you run python main.py , there is no problem at first. But when the ui comes out and clicks after that, it stops.
The error message is this:

(styleflow) PS C:\Users\isack\Documents\StyleFlow> python main.py
----------------- Options ---------------
                batchSize: 1
          checkpoints_dir: ./checkpoints
                 dataroot: ./data/datasetX
                  gpu_ids: 0
     max_result_snapshots: 30
                    model: xxxx
                     name: XXXX
              network_pkl: gdrive:networks/stylegan2-ffhq-config-f.pkl
            only_for_test: ...
                    phase: test
----------------- End -------------------
Loading networks from "gdrive:networks/stylegan2-ffhq-config-f.pkl"...
Setting up TensorFlow plugin "fused_bias_act.cu": Preprocessing... Loading... Done.
Setting up TensorFlow plugin "upfirdn_2d.cu": Preprocessing... Loading... Done.
Training T : 1.0
Number of trainable parameters of Point CNF: 1691649
Traceback (most recent call last):
  File "C:\Users\isack\Documents\StyleFlow\ui\mouse_event.py", line 39, in mousePressEvent
    self.showImage(self.point)
  File "C:\Users\isack\Documents\StyleFlow\ui\mouse_event.py", line 71, in showImage
    self.Form.update_GT_scene_image()
  File "main.py", line 158, in update_GT_scene_image
    self.fws = self.prior(self.q_array, self.final_array_source, self.zero_padding)
  File "C:\Users\isack\Anaconda3\envs\styleflow\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\isack\Documents\StyleFlow\module\cnf.py", line 30, in forward
    x, logpx = self.chain[i](x, context, logpx, integration_times, reverse)
  File "C:\Users\isack\Anaconda3\envs\styleflow\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\isack\Documents\StyleFlow\module\cnf.py", line 105, in forward
    method=self.test_solver,
  File "C:\Users\isack\Anaconda3\envs\styleflow\lib\site-packages\torchdiffeq\_impl\adjoint.py", line 129, in odeint_adjoint
    ys = OdeintAdjointMethod.apply(*y0, func, t, flat_params, rtol, atol, method, options)
  File "C:\Users\isack\Anaconda3\envs\styleflow\lib\site-packages\torchdiffeq\_impl\adjoint.py", line 18, in forward
    ans = odeint(func, y0, t, rtol=rtol, atol=atol, method=method, options=options)
  File "C:\Users\isack\Anaconda3\envs\styleflow\lib\site-packages\torchdiffeq\_impl\odeint.py", line 76, in odeint
    solution = solver.integrate(t)
  File "C:\Users\isack\Anaconda3\envs\styleflow\lib\site-packages\torchdiffeq\_impl\solvers.py", line 29, in integrate
    self.before_integrate(t)
  File "C:\Users\isack\Anaconda3\envs\styleflow\lib\site-packages\torchdiffeq\_impl\dopri5.py", line 78, in before_integrate
    f0 = self.func(t[0].type_as(self.y0[0]), self.y0)
  File "C:\Users\isack\Anaconda3\envs\styleflow\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\isack\Documents\StyleFlow\module\odefunc.py", line 133, in forward
    dy = self.diffeq(tc, y)
  File "C:\Users\isack\Anaconda3\envs\styleflow\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\isack\Documents\StyleFlow\module\odefunc.py", line 97, in forward
    dx = layer(context, dx)
  File "C:\Users\isack\Anaconda3\envs\styleflow\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\isack\Documents\StyleFlow\module\diffeq_layers.py", line 86, in forward
    ret = self._layer(x) * gate + bias
  File "C:\Users\isack\Anaconda3\envs\styleflow\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\isack\Anaconda3\envs\styleflow\lib\site-packages\torch\nn\modules\linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\isack\Anaconda3\envs\styleflow\lib\site-packages\torch\nn\functional.py", line 1371, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by leeisack** [comment]
Additionally, my output in web ui.
![image](https://user-images.githubusercontent.com/52061393/139797753-e55e1920-0805-466b-a3d8-702fe8f03da4.png)

**Comment by vicdxxx** [comment]
> 

Do you use cuda 10.0 with cudnn?
