### ISSUE TITLE
RuntimeError: No GPU devices found

### ISSUE THREAD

**Issue by orydatadudes** [RameenAbdal/StyleFlow#39]
when trying to run main.py i am getting the following error

  File "/home/projects/StyleFlow/main.py", line 365, in <module>
    ex = ExWindow(opt)
  File "/home/projects/StyleFlow/main.py", line 40, in __init__
    self.EX = Ex(opt)
  File "/home/projects/StyleFlow/main.py", line 70, in __init__
    self.init_deep_model(opt)
  File "/home/projects/StyleFlow/main.py", line 105, in init_deep_model
    self.model = Build_model(self.opt)
  File "/home/projects/StyleFlow/utils.py", line 200, in __init__
    _G, _D, Gs = pretrained_networks.load_networks(network_pkl)
  File "/home/projects/StyleFlow/pretrained_networks.py", line 76, in load_networks
    G, D, Gs = pickle.load(stream, encoding='latin1')
  File "/home/projects/StyleFlow/dnnlib/tflib/network.py", line 297, in __setstate__
    self._init_graph()
  File "/home/projects/StyleFlow/dnnlib/tflib/network.py", line 154, in _init_graph
    out_expr = self._build_func(*self.input_templates, **build_kwargs)
  File "<string>", line 491, in G_synthesis_stylegan2
  File "<string>", line 455, in layer
  File "<string>", line 99, in modulated_conv2d_layer
  File "<string>", line 68, in apply_bias_act
  File "/home/projects/StyleFlow/dnnlib/tflib/ops/fused_bias_act.py", line 68, in fused_bias_act
    return impl_dict[impl](x=x, b=b, axis=axis, act=act, alpha=alpha, gain=gain)
  File "/home/projects/StyleFlow/dnnlib/tflib/ops/fused_bias_act.py", line 122, in _fused_bias_act_cuda
    cuda_kernel = _get_plugin().fused_bias_act
  File "/home/projects/StyleFlow/dnnlib/tflib/ops/fused_bias_act.py", line 16, in _get_plugin
    return custom_ops.get_plugin(os.path.splitext(__file__)[0] + '.cu')
  File "/home/projects/StyleFlow/dnnlib/tflib/custom_ops.py", line 132, in get_plugin
    compile_opts += ' --gpu-architecture=%s' % _get_cuda_gpu_arch_string()
  File "/home/projects/StyleFlow/dnnlib/tflib/custom_ops.py", line 52, in _get_cuda_gpu_arch_string
    raise RuntimeError('No GPU devices found')
RuntimeError: No GPU devices found
 what can be the problem

**Comment by RameenAbdal** [comment]
You would require a GPU enabled a system to run this code. Please refer to the requirements.

**Comment by orydatadudes** [comment]
also i case i went to use cpu? ( by setting gpu_ids = "-1")

**Comment by filipppp** [comment]
Well my GTX 1050 in my Laptop is also not recognized:

`ke to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Failed!
Traceback (most recent call last):
  File "main.py", line 365, in <module>
    ex = ExWindow(opt)
  File "main.py", line 40, in __init__
    self.EX = Ex(opt)
  File "main.py", line 70, in __init__
    self.init_deep_model(opt)
  File "main.py", line 105, in init_deep_model
    self.model = Build_model(self.opt)
  File "/home/filip/Desktop/StyleFlow/utils.py", line 200, in __init__
    _G, _D, Gs = pretrained_networks.load_networks(network_pkl)
  File "/home/filip/Desktop/StyleFlow/pretrained_networks.py", line 76, in load_networks
    G, D, Gs = pickle.load(stream, encoding='latin1')
  File "/home/filip/Desktop/StyleFlow/dnnlib/tflib/network.py", line 297, in __setstate__
    self._init_graph()
  File "/home/filip/Desktop/StyleFlow/dnnlib/tflib/network.py", line 154, in _init_graph
    out_expr = self._build_func(*self.input_templates, **build_kwargs)
  File "<string>", line 491, in G_synthesis_stylegan2
  File "<string>", line 455, in layer
  File "<string>", line 99, in modulated_conv2d_layer
  File "<string>", line 68, in apply_bias_act
  File "/home/filip/Desktop/StyleFlow/dnnlib/tflib/ops/fused_bias_act.py", line 68, in fused_bias_act
    return impl_dict[impl](x=x, b=b, axis=axis, act=act, alpha=alpha, gain=gain)
  File "/home/filip/Desktop/StyleFlow/dnnlib/tflib/ops/fused_bias_act.py", line 122, in _fused_bias_act_cuda
    cuda_kernel = _get_plugin().fused_bias_act
  File "/home/filip/Desktop/StyleFlow/dnnlib/tflib/ops/fused_bias_act.py", line 16, in _get_plugin
    return custom_ops.get_plugin(os.path.splitext(__file__)[0] + '.cu')
  File "/home/filip/Desktop/StyleFlow/dnnlib/tflib/custom_ops.py", line 132, in get_plugin
    compile_opts += ' --gpu-architecture=%s' % _get_cuda_gpu_arch_string()
  File "/home/filip/Desktop/StyleFlow/dnnlib/tflib/custom_ops.py", line 52, in _get_cuda_gpu_arch_string
    raise RuntimeError('No GPU devices found')
RuntimeError: No GPU devices found
`

My nvidia-smi:

`Tue Jan 19 13:24:00 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P3    N/A /  N/A |   1836MiB /  4042MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1371      G   /usr/lib/xorg/Xorg                           133MiB |
|    0      2177      G   /usr/lib/xorg/Xorg                           740MiB |
|    0      2436      G   /usr/bin/gnome-shell                         376MiB |
|    0     39246      G   ...AAAAAAAAAAAACAAAAAAAAAA= --shared-files   128MiB |
|    0    303512      G   .../share/spotify/debug.log --shared-files   145MiB |
|    0    309925      G   ...AAAAAAAAAAAIAAAAAAAAAA== --shared-files   297MiB |
+-----------------------------------------------------------------------------+
`

and nvcc:

`
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

`

**Comment by Minabsapi** [comment]
My desktop GT730 is also not recognized, despite having installed CUDA 11.2 and everything tensorflow requires. GNU/Linux Ubuntu 20.04, Cuda compilation tools release 10.1 (V10.1.243)

Traceback:
```
WARNING: Logging before flag parsing goes to stderr.
W0807 02:19:49.502065 140405207926592 deprecation.py:323] From /home/minabsapi/anaconda3/envs/StyleFlow/lib/python3.7/site-packages/tensorflow_core/python/compat/v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
----------------- Options ---------------
                batchSize: 1                             
          checkpoints_dir: ./checkpoints                 
                 dataroot: ./data/datasetX               
                  gpu_ids: 0                             
     max_result_snapshots: 30                            
                    model: xxxx                          
                     name: XXXX                          
              network_pkl: gdrive:networks/stylegan2-ffhq-config-f.pkl
            only_for_test: ...                           
                    phase: test                          
----------------- End -------------------
Loading networks from "gdrive:networks/stylegan2-ffhq-config-f.pkl"...
Downloading http://d36zk2xti64re0.cloudfront.net/stylegan2/networks/stylegan2-ffhq-config-f.pkl ... done
2021-08-07 02:24:33.873939: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type; LD_LIBRARY_PATH: :/usr/local/cuda/lib64
2021-08-07 02:24:33.874142: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type; LD_LIBRARY_PATH: :/usr/local/cuda/lib64
2021-08-07 02:24:33.874331: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type; LD_LIBRARY_PATH: :/usr/local/cuda/lib64
2021-08-07 02:24:33.874501: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type; LD_LIBRARY_PATH: :/usr/local/cuda/lib64
2021-08-07 02:24:33.874669: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type; LD_LIBRARY_PATH: :/usr/local/cuda/lib64
2021-08-07 02:24:33.874835: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type; LD_LIBRARY_PATH: :/usr/local/cuda/lib64
2021-08-07 02:24:33.875002: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type; LD_LIBRARY_PATH: :/usr/local/cuda/lib64
2021-08-07 02:24:33.875025: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Setting up TensorFlow plugin "fused_bias_act.cu": Preprocessing... 2021-08-07 02:24:38.200614: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type; LD_LIBRARY_PATH: :/usr/local/cuda/lib64
2021-08-07 02:24:38.200732: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type; LD_LIBRARY_PATH: :/usr/local/cuda/lib64
2021-08-07 02:24:38.200853: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type; LD_LIBRARY_PATH: :/usr/local/cuda/lib64
2021-08-07 02:24:38.200958: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type; LD_LIBRARY_PATH: :/usr/local/cuda/lib64
2021-08-07 02:24:38.201064: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type; LD_LIBRARY_PATH: :/usr/local/cuda/lib64
2021-08-07 02:24:38.201167: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type; LD_LIBRARY_PATH: :/usr/local/cuda/lib64
2021-08-07 02:24:38.201273: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type; LD_LIBRARY_PATH: :/usr/local/cuda/lib64
2021-08-07 02:24:38.201285: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Failed!
Traceback (most recent call last):
  File "main.py", line 367, in <module>
    ex = ExWindow(opt)
  File "main.py", line 42, in __init__
    self.EX = Ex(opt)
  File "main.py", line 72, in __init__
    self.init_deep_model(opt)
  File "main.py", line 107, in init_deep_model
    self.model = Build_model(self.opt)
  File "/media/minabsapi/16e8b3e4-5567-4c10-b6be-e686bc2a6132/home/minabsapi/Téléchargements/StyleFlow/utils.py", line 202, in __init__
    _G, _D, Gs = pretrained_networks.load_networks(network_pkl)
  File "/media/minabsapi/16e8b3e4-5567-4c10-b6be-e686bc2a6132/home/minabsapi/Téléchargements/StyleFlow/pretrained_networks.py", line 76, in load_networks
    G, D, Gs = pickle.load(stream, encoding='latin1')
  File "/media/minabsapi/16e8b3e4-5567-4c10-b6be-e686bc2a6132/home/minabsapi/Téléchargements/StyleFlow/dnnlib/tflib/network.py", line 299, in __setstate__
    self._init_graph()
  File "/media/minabsapi/16e8b3e4-5567-4c10-b6be-e686bc2a6132/home/minabsapi/Téléchargements/StyleFlow/dnnlib/tflib/network.py", line 156, in _init_graph
    out_expr = self._build_func(*self.input_templates, **build_kwargs)
  File "<string>", line 491, in G_synthesis_stylegan2
  File "<string>", line 455, in layer
  File "<string>", line 99, in modulated_conv2d_layer
  File "<string>", line 68, in apply_bias_act
  File "/media/minabsapi/16e8b3e4-5567-4c10-b6be-e686bc2a6132/home/minabsapi/Téléchargements/StyleFlow/dnnlib/tflib/ops/fused_bias_act.py", line 70, in fused_bias_act
    return impl_dict[impl](x=x, b=b, axis=axis, act=act, alpha=alpha, gain=gain)
  File "/media/minabsapi/16e8b3e4-5567-4c10-b6be-e686bc2a6132/home/minabsapi/Téléchargements/StyleFlow/dnnlib/tflib/ops/fused_bias_act.py", line 124, in _fused_bias_act_cuda
    cuda_kernel = _get_plugin().fused_bias_act
  File "/media/minabsapi/16e8b3e4-5567-4c10-b6be-e686bc2a6132/home/minabsapi/Téléchargements/StyleFlow/dnnlib/tflib/ops/fused_bias_act.py", line 18, in _get_plugin
    return custom_ops.get_plugin(os.path.splitext(__file__)[0] + '.cu')
  File "/media/minabsapi/16e8b3e4-5567-4c10-b6be-e686bc2a6132/home/minabsapi/Téléchargements/StyleFlow/dnnlib/tflib/custom_ops.py", line 135, in get_plugin
    compile_opts += ' --gpu-architecture=%s' % _get_cuda_gpu_arch_string()
  File "/media/minabsapi/16e8b3e4-5567-4c10-b6be-e686bc2a6132/home/minabsapi/Téléchargements/StyleFlow/dnnlib/tflib/custom_ops.py", line 54, in _get_cuda_gpu_arch_string
    raise RuntimeError('No GPU devices found')
RuntimeError: No GPU devices found
```

nvidia-smi:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GT 730      Off  | 00000000:01:00.0 N/A |                  N/A |
| 40%   53C    P0    N/A /  N/A |    582MiB /  1994MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
