### ISSUE TITLE
Can't Even Open The GUI: gcc versions later than 7 are not supported!

### ISSUE THREAD

**Issue by Tuba202** [RameenAbdal/StyleFlow#74]
**I am running linux mint with a gtx 1080. When I try to run the program, I get this error:**
```
----------------- Options ---------------
                batchSize: 1                             
          checkpoints_dir: ./checkpoints                 
                 dataroot: ./data/datasetX               
                  gpu_ids: 0                             
     max_result_snapshots: 30                            
                    model: xxxx                          
                     name: XXXX                          
              network_pkl: gdrive:networks/stylegan2-ffhq-config-f.pkl
            only_for_test: ...                           
                    phase: test                          
----------------- End -------------------
Loading networks from "gdrive:networks/stylegan2-ffhq-config-f.pkl"...
Setting up TensorFlow plugin "fused_bias_act.cu": Preprocessing... Failed!
Traceback (most recent call last):
  File "main.py", line 365, in <module>
    ex = ExWindow(opt)
  File "main.py", line 40, in __init__
    self.EX = Ex(opt)
  File "main.py", line 70, in __init__
    self.init_deep_model(opt)
  File "main.py", line 105, in init_deep_model
    self.model = Build_model(self.opt)
  File "/home/elliotmarks/StyleFlow/utils.py", line 200, in __init__
    _G, _D, Gs = pretrained_networks.load_networks(network_pkl)
  File "/home/elliotmarks/StyleFlow/pretrained_networks.py", line 76, in load_networks
    G, D, Gs = pickle.load(stream, encoding='latin1')
  File "/home/elliotmarks/StyleFlow/dnnlib/tflib/network.py", line 297, in __setstate__
    self._init_graph()
  File "/home/elliotmarks/StyleFlow/dnnlib/tflib/network.py", line 154, in _init_graph
    out_expr = self._build_func(*self.input_templates, **build_kwargs)
  File "<string>", line 491, in G_synthesis_stylegan2
  File "<string>", line 455, in layer
  File "<string>", line 99, in modulated_conv2d_layer
  File "<string>", line 68, in apply_bias_act
  File "/home/elliotmarks/StyleFlow/dnnlib/tflib/ops/fused_bias_act.py", line 68, in fused_bias_act
    return impl_dict[impl](x=x, b=b, axis=axis, act=act, alpha=alpha, gain=gain)
  File "/home/elliotmarks/StyleFlow/dnnlib/tflib/ops/fused_bias_act.py", line 122, in _fused_bias_act_cuda
    cuda_kernel = _get_plugin().fused_bias_act
  File "/home/elliotmarks/StyleFlow/dnnlib/tflib/ops/fused_bias_act.py", line 16, in _get_plugin
    return custom_ops.get_plugin(os.path.splitext(__file__)[0] + '.cu')
  File "/home/elliotmarks/StyleFlow/dnnlib/tflib/custom_ops.py", line 113, in get_plugin
    _run_cmd(_prepare_nvcc_cli('"%s" --preprocess -o "%s" --keep --keep-dir "%s"' % (cuda_file, tmp_file, tmp_dir)))
  File "/home/elliotmarks/StyleFlow/dnnlib/tflib/custom_ops.py", line 61, in _run_cmd
    raise RuntimeError('NVCC returned an error. See below for full command line and output log:\n\n%s\n\n%s' % (cmd, output))
RuntimeError: NVCC returned an error. See below for full command line and output log:

/usr/local/cuda/bin/nvcc --std=c++11 -DNDEBUG "/home/elliotmarks/StyleFlow/dnnlib/tflib/ops/fused_bias_act.cu" --preprocess -o "/tmp/tmpq3ue5ojw/fused_bias_act_tmp.cu" --keep --keep-dir "/tmp/tmpq3ue5ojw" --disable-warnings --include-path "/home/elliotmarks/miniconda3/envs/styleflow/lib/python3.6/site-packages/tensorflow_core/include" --include-path "/home/elliotmarks/miniconda3/envs/styleflow/lib/python3.6/site-packages/tensorflow_core/include/external/protobuf_archive/src" --include-path "/home/elliotmarks/miniconda3/envs/styleflow/lib/python3.6/site-packages/tensorflow_core/include/external/com_google_absl" --include-path "/home/elliotmarks/miniconda3/envs/styleflow/lib/python3.6/site-packages/tensorflow_core/include/external/eigen_archive" 2>&1

In file included from /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/host_config.h:129:2: error: #error -- unsupported GNU version! gcc versions later than 7 are not supported!
  129 | #error -- unsupported GNU version! gcc versions later than 7 are not supported!
      |  ^~~~~
```

**What can I do to fix this?**

**Comment by Tuba202** [comment]
I somehow reinstalled and got it fixed.
